# Generated by Django 5.2.13 on 2026-04-19 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materiel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('refusee', 'Refusée'), ('en_cours', 'En cours'), ('restituee', 'Restituée')], default='en_attente', max_length=20)),
                ('motif', models.TextField(blank=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Emplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('adresse', models.TextField(blank=True)),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emplacement', to='emprunts.demande')),
            ],
        ),
        migrations.CreateModel(
            name='LigneDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='emprunts.demande')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_demande', to='materiel.materiel')),
            ],
        ),
        migrations.CreateModel(
            name='Restitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_retour', models.DateTimeField(auto_now_add=True)),
                ('etat_materiel', models.CharField(choices=[('bon', 'Bon état'), ('abime', 'Abîmé'), ('perdu', 'Perdu')], default='bon', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='restitutions/photos/')),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restitution', to='emprunts.demande')),
            ],
        ),
    ]
