# Generated by Django 5.2.13 on 2026-04-26 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprunts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='date_debut',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='demande',
            name='date_fin',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='ZoneAutorisee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude_centre', models.FloatField()),
                ('longitude_centre', models.FloatField()),
                ('rayon_km', models.FloatField(default=50)),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zone_autorisee', to='emprunts.demande')),
            ],
        ),
    ]
