# Generated by Django 5.2.13 on 2026-04-26 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprunts', '0002_alter_demande_date_debut_alter_demande_date_fin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionTempsReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='emprunts.demande')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
