# Generated by Django 5.2.13 on 2026-05-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprunts', '0003_positiontempsreel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('refusee', 'Refusée'), ('en_cours', 'En cours'), ('en_attente_restitution', 'En attente de vérification'), ('restituee', 'Restituée')], default='en_attente', max_length=30),
        ),
    ]
