# Generated by Django 5.2.13 on 2026-04-19 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('etat', models.CharField(choices=[('disponible', 'Disponible'), ('emprunte', 'Emprunté'), ('maintenance', 'En maintenance'), ('hors_service', 'Hors service')], default='disponible', max_length=20)),
                ('photo', models.ImageField(blank=True, upload_to='materiels/photos/')),
                ('description', models.TextField(blank=True)),
                ('date_acquisition', models.DateField(blank=True, null=True)),
                ('code_qr', models.ImageField(blank=True, upload_to='materiels/qrcodes/')),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiels', to='materiel.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('panne', 'Panne'), ('entretien', 'Entretien'), ('reparation', 'Réparation')], max_length=20)),
                ('date_signalement', models.DateField(auto_now_add=True)),
                ('date_resolution', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('resolu', 'Résolu'), ('en_attente', 'En attente')], default='en_attente', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='materiel.materiel')),
            ],
        ),
    ]
