# Generated by Django 5.2.13 on 2026-05-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiel',
            name='quantite_disponible',
            field=models.IntegerField(default=1, verbose_name='Quantité disponible'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='quantite_stock',
            field=models.IntegerField(default=1, verbose_name='Quantité en stock'),
        ),
    ]
