# Generated by Django 5.2.13 on 2026-05-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiel', '0002_materiel_quantite_disponible_materiel_quantite_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiel',
            name='domaine',
            field=models.CharField(choices=[('terrain', 'Terrain'), ('bureau', 'Bureau')], default='bureau', max_length=20),
        ),
    ]
