# Generated by Django 5.2.13 on 2026-04-19 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cahier', '0002_initial'),
        ('emprunts', '0001_initial'),
        ('materiel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='clubs/logos/')),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('cotisation_montant', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant cotisation (FCFA)')),
                ('materiel_propre', models.ManyToManyField(blank=True, related_name='clubs_proprietaires', to='materiel.materiel', verbose_name='Matériel propre au club')),
            ],
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('conference', 'Conférence'), ('sortie', 'Sortie pédagogique'), ('jpo', 'Journée portes ouvertes'), ('atelier', 'Atelier'), ('cours', 'Cours / Formation'), ('competition', 'Compétition'), ('autre', 'Autre')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('lieu', models.CharField(blank=True, max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20)),
                ('photo_principale', models.ImageField(blank=True, upload_to='clubs/activites/')),
                ('programme', models.FileField(blank=True, upload_to='clubs/programmes/')),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites', to='emprunts.demande')),
                ('seance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites_clubs', to='cahier.seance')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='clubs.club')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lien', models.CharField(blank=True, max_length=200)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='clubs/galerie/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='clubs.activite')),
            ],
        ),
        migrations.CreateModel(
            name='MembreClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('president', 'Président'), ('vice_president', 'Vice-Président'), ('secretaire', 'Secrétaire'), ('membre', 'Membre')], default='membre', max_length=20)),
                ('date_adhesion', models.DateField(auto_now_add=True)),
                ('cotisation_payee', models.BooleanField(default=False)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='clubs.club')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appartenances_clubs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('club', 'utilisateur')},
            },
        ),
    ]
