# Generated by Django 5.2.13 on 2026-05-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='carte_etudiant',
            field=models.ImageField(blank=True, null=True, upload_to='cartes_etudiants/'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='departement',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='fonction',
            field=models.CharField(blank=True, choices=[('professeur', 'Professeur'), ('maitre_assistant', 'Maître Assistant'), ('maitre_conference', 'Maître de Conférences'), ('vacataire', 'Vacataire'), ('chef_departement', 'Chef de Département')], max_length=30),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profils/'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='niveau',
            field=models.CharField(blank=True, choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('D', 'Doctorat')], max_length=10),
        ),
    ]
