# Generated by Django 5.2.13 on 2026-04-19 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cahier', '0001_initial'),
        ('emprunts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='demande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances', to='emprunts.demande'),
        ),
        migrations.AddField(
            model_name='seance',
            name='enseignant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fichierseance',
            name='seance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='cahier.seance'),
        ),
    ]
