# Generated by Django 5.2.13 on 2026-05-14 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cahier', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seance',
            options={'ordering': ['-date', '-heure_debut']},
        ),
        migrations.AddField(
            model_name='cours',
            name='enseignant',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'enseignant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours_assignes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cours',
            name='volume_horaire',
            field=models.IntegerField(default=0, verbose_name='Volume horaire prévu (h)'),
        ),
        migrations.AddField(
            model_name='seance',
            name='duree',
            field=models.FloatField(default=0, verbose_name='Durée (heures)'),
        ),
        migrations.AddField(
            model_name='seance',
            name='heure_debut',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seance',
            name='heure_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seance',
            name='valide',
            field=models.BooleanField(default=False, verbose_name='Validée par le chef'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='contenu',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justifie', models.BooleanField(default=False)),
                ('motif', models.TextField(blank=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to=settings.AUTH_USER_MODEL)),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='cahier.seance')),
            ],
            options={
                'unique_together': {('seance', 'etudiant')},
            },
        ),
    ]
