# Generated by Django 5.2.13 on 2026-05-14 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cahier', '0003_alter_seance_options_cours_enseignant_and_more'),
        ('emprunts', '0004_alter_demande_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('cours', 'Cours'), ('conference', 'Conférence'), ('club', 'Activité club'), ('sortie', 'Sortie terrain'), ('examen', 'Examen'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('confirme', 'Confirmé'), ('annule', 'Annulé'), ('termine', 'Terminé')], default='planifie', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('lieu', models.CharField(blank=True, max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements', to='cahier.cours')),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements', to='emprunts.demande')),
                ('organisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements_organises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_debut', 'heure_debut'],
            },
        ),
    ]
